### ISSUE TITLE
Better Errors while reading Dataset

### ISSUE THREAD

**Issue by Muziwahuzie** [lm-pub-quiz/lm-pub-quiz#11]
Hi there @plonerma 
When loading a Dataset, while having dot files (hidden files) in the dataset folder, leads to an error message, that is not much of a help.

Here is the traceback:

Traceback (most recent call last):
 File "/path/to/pythonscript/collect_data.py", line 52, in <module>
   DataCollection().run()
   ^^^^^^^^^^^^^^^^
 File "/path/to/pythonscript/collect_data.py", line 25, in __init__
   self.dataset = Dataset.from_path("dataset/location-test")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/path/to/lm-pub-quiz/src/lm_pub_quiz/data/dataset.py", line 298, in from_path
   relations = [Relation.from_path(p, lazy=lazy) for p in relation_files]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/path/to/lm-pub-quiz/src/lm_pub_quiz/data/dataset.py", line 152, in from_path
   raise ValueError(msg)
ValueError: A path to a directory was passed but no relation was specified.

In this case a .ipynb_checkpoints folder was inside the dataset, which gets generated, by jupyter lab.

I could work on a solution for this. 

Do you need something else from me?

**Comment by plonerma** [comment]
Thanks for describing the issue. It should be fixed in #13.
